export const STAKE_LEVELS = {
  practice: {
    id: 'practice',
    label: 'Practice',
    entryFee: 0,
    potMultiplier: 0,
    rakePercent: 0,
    minPlayers: 2,
    maxPlayers: 5,
    botEnabled: true,
    color: '#00C853',
    badge: '🎯 Free',
    launchEnabled: true,
  },
  bronze: {
    id: 'bronze',
    label: 'Bronze',
    entryFee: 20000,
    potMultiplier: 0.9,
    rakePercent: 10,
    minPlayers: 2,
    maxPlayers: 5,
    botEnabled: true,
    color: '#CD7F32',
    badge: '🥉 ₦200',
    launchEnabled: true,
  },
  silver: {
    id: 'silver',
    label: 'Silver',
    entryFee: 50000,
    potMultiplier: 0.9,
    rakePercent: 10,
    minPlayers: 2,
    maxPlayers: 5,
    botEnabled: true,
    color: '#C0C0C0',
    badge: '🥈 ₦500',
    launchEnabled: true,
  },
  gold: {
    id: 'gold',
    label: 'Gold',
    entryFee: 200000,
    potMultiplier: 0.9,
    rakePercent: 10,
    minPlayers: 2,
    maxPlayers: 5,
    botEnabled: true,
    color: '#FFD700',
    badge: '🥇 ₦2,000',
    launchEnabled: false,
  },
  diamond: {
    id: 'diamond',
    label: 'Diamond',
    entryFee: 500000,
    potMultiplier: 0.9,
    rakePercent: 10,
    minPlayers: 2,
    maxPlayers: 5,
    botEnabled: true,
    color: '#1E90FF',
    badge: '💎 ₦5,000',
    launchEnabled: false,
  },
} as const

export type StakeLevel = keyof typeof STAKE_LEVELS
